name: Deploy to Namecheap

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    name: SSH (rsync) Deploy to Namecheap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH (rsync) to Namecheap
        uses: Burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete --exclude='.git*' --exclude='.github/**' --exclude='node_modules/**' --exclude='.gitignore' --exclude='data/site.php' --exclude='data/auth.php' --exclude='data/throttle.php' --exclude='data/.lock' --exclude='uploads/**'
          path: ./
          remote_path: ${{ secrets.SSH_TARGET_DIR }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_port: ${{ secrets.SSH_PORT }}
